## Importación de Bibliotecas

In [2]:
import numpy as np

## Dimenciones y Forma de Arreglos 

### Escalares

In [ ]:
escalar = np.array(7)

print(f'Escalar: {escalar}')
print(f'Dimensiones: {escalar.ndim}')
print(f'Forma: {escalar.shape}')
print(f'Tamaño: {escalar.size}')
print(f'Tipo de datos: {escalar.dtype}')

Escalar: 7
Dimensiones: 0
Forma: ()
Tamaño: 1
Tipo de datos: int64


### Vectores

In [5]:
vector= np.array([1, 2, 3, 4, 5])

print(f'Vector: {vector}')
print(f'Dimensiones: {vector.ndim}')
print(f'Forma: {vector.shape}')
print(f'Tamaño: {vector.size}')
print(f'Tipo de datos: {vector.dtype}')

Vector: [1 2 3 4 5]
Dimensiones: 1
Forma: (5,)
Tamaño: 5
Tipo de datos: int64


### Matrices

In [6]:
matriz= np.array([[1, 2, 3], [4, 5, 6]])

print(f'Matriz: \n{matriz}')
print(f'Dimensiones: {matriz.ndim}')
print(f'Forma: {matriz.shape}')
print(f'Tamaño: {matriz.size}')
print(f'Tipo de datos: {matriz.dtype}')

Matriz: 
[[1 2 3]
 [4 5 6]]
Dimensiones: 2
Forma: (2, 3)
Tamaño: 6
Tipo de datos: int64


### Tenosor 3D

In [7]:
tensor_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(f'Tensor 3D: \n{tensor_3d}')
print(f'Dimensiones: {tensor_3d.ndim}')
print(f'Forma: {tensor_3d.shape}')
print(f'Tamaño: {tensor_3d.size}')
print(f'Tipo de datos: {tensor_3d.dtype}')

Tensor 3D: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimensiones: 3
Forma: (2, 2, 3)
Tamaño: 12
Tipo de datos: int64


## Reshape de Arreglos

In [8]:
tensor_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

### De Tensor 3D a Vector

In [10]:
vector_reshaped=np.reshape(tensor_3d, (12,))
print(f'Vector reshaped: \n{vector_reshaped}')

Vector reshaped: 
[ 1  2  3  4  5  6  7  8  9 10 11 12]


### De Tensor 3D a Matriz 2D

In [9]:
matriz_reshaped=np.reshape(tensor_3d, (4, 3))
print(f'Matriz reshaped: \n{matriz_reshaped}')

Matriz reshaped: 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Transposición de Arreglos

### Transpuesta de un Tesor 3D

In [13]:
Tensor_Transpuesto = np.transpose(tensor_3d)
print(f'Tensor 3D transpuesto: \n{Tensor_Transpuesto}')

Tensor 3D transpuesto: 
[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


### Transpuesta de una Matriz 2D

In [12]:
Matriz_Transpuesta = np.transpose(matriz)
print(f'Matriz 2D transpuesta: \n{Matriz_Transpuesta}')

Matriz 2D transpuesta: 
[[1 4]
 [2 5]
 [3 6]]
